### ISSUE TITLE
How would banner such as Black Friday work

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#1012]
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/1009

### Description

n/a

**Comment by stevenbister** [comment]
Blocked until I can have catch up with Marketing on 3/8/23

**Comment by stevenbister** [comment]
Marketing happy with approach, now blocked until we can get https://github.com/Open-Study-College/osc/pull/1382 merged
