### ISSUE TITLE
Managing user personal data

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#1041]
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/1040

### Description

First Name
Last Name
Email
Telephone
Date of Birth
Postcode/Address
Gender
Nationality
SEN
Bio
Avatar
Additional Notes
Password

**Comment by Tom-Pearce** [comment]
Integration with hubspot

**Comment by hi-im-si** [comment]
Requires integration with Hubspot
