### ISSUE TITLE
Get list of students

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#1052]
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/1051

### Description

n/a

**Comment by hi-im-si** [comment]
This will be the beginning of quite a large query.
This will need to be super flexible and dynamic.
Can be used to list students, tutors and IV's

**Comment by hi-im-si** [comment]
This will firstly be used to list students and then the other user types will come thereafter
