### ISSUE TITLE
Research Exit Intent

### ISSUE THREAD

**Issue by hi-im-si** [Open-Study-College/osc#1246]
Story: #1013 

Research Exit Intent Popup.
Currently uses Optinmonster. Is this something we want to continue with or find a suitable alternative.
Marketing team are not overly complimentary of optinmonster and open to suggestions

**Comment by stevenbister** [comment]
Being reviewed by Marketing

**Comment by stevenbister** [comment]
Sharnie has confirmed Poptin is her preferred choice
