### ISSUE TITLE
Course cards in instantsearch - Prices to be updated

### ISSUE THREAD

**Issue by stevenbister** [Open-Study-College/osc#1279]
### Description

Course cards say "from £XXX per month" I would expect this to be the lowest price available to the product, however it appears to be displaying the highest

### Link to Reproduction

http://localhost:2000/collections/a-levels

### Steps to reproduce

Go to a collections page such as collections/a-levels

![image](https://github.com/Open-Study-College/osc/assets/23461173/15f4e9e6-9f06-461e-a773-74070ba26489)

You will see the course cards displaying the courses with the price in the top corner. In this case you will see a level biology is "from £1609 in full" however if you click on the course then the lowest price is actually "£468 in full".

![image](https://github.com/Open-Study-College/osc/assets/23461173/5e1c4baa-543c-4ca8-a0fb-348af35ddef5)

### Release Version

0.142.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by hi-im-si** [comment]
Potentially utilising a `min variant price`

**Comment by mattwendzina** [comment]
We need to add the lowest monthly price metafield from shopify (once it has been synced to Algolia) AND add the lowest price for a course (which is already Algolia)
