### ISSUE TITLE
Research Data Table Component

### ISSUE THREAD

**Issue by hi-im-si** [Open-Study-College/osc#1345]
### Link task to story

Story: #276

### Description

Research data table component primitives to use for build.
Maybe create an ADR

**Comment by stevenbister** [comment]
Some potential candidates 

- https://tanstack.com/table/v8
- https://react-spectrum.adobe.com/react-aria/Table.html / https://react-spectrum.adobe.com/react-aria/useTable.html
- https://ui.shadcn.com/docs/components/data-table

**Comment by stevenbister** [comment]
ADR submitted https://www.notion.so/openstudycollege/Decision-Data-Table-Component-Primitive-52c664be3f814eda84bf7d68570b3af5?pvs=4
