### ISSUE TITLE
Create tutor cards - 

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#1499]
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/1479

### Description

n/a

**Comment by stevenbister** [comment]
![Image](https://github.com/Open-Study-College/osc/assets/23461173/8dd64060-a2f4-45bd-9ca1-905f876880ea)



![Image](https://github.com/Open-Study-College/osc/assets/23461173/a762e0ca-a52d-4f6f-a1dc-224f63df789c)
