### ISSUE TITLE
Remove wishlists from course card

### ISSUE THREAD

**Issue by mattwendzina** [Open-Study-College/osc#1594]
### Link task to story

Story: 

### Description

Need to remove WishLists from the InstantSearchCourseCard (possibly other places too?) as we don't have this functionality in place yet.

**Comment by hi-im-si** [comment]
Remove all "Heart" buttons from the build temporarily as we do not use wishlists currently.

**Comment by hi-im-si** [comment]
/collections/name-of-collection
/cart
