### ISSUE TITLE
[S4.8]: Build ML Search bar and Recommendations Grids

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#196]
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

N/a

### Linked Tasks

- [x] #197 
- [x] #198 
- [x] #199 
- [x] #200 
- [x] #201 
- [x] #202 
- [x] #203 
- [x] #899 
- [x] #900 
- [x] #932 
- [x] #938 
- [x] #1135 
- [x] #1137 
- [x] #1238

**Comment by aaacafe786** [comment]
need to refactor this task
