### ISSUE TITLE
[S10.1]: List

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#211]
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

n/a

### Linked Tasks

- [x] #212

**Comment by stevenbister** [comment]
Hey! @hi-im-si @aaacafe786 

In terms of adding things like the list component to `osc-ui` is it simply to allow us to put the styling on it? Obviously there's not too much to do to this other than add a class name
https://chakra-ui.com/docs/components/list/usage
