### ISSUE TITLE
[S11.1]: Video

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#214]
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

n/a

### Linked Tasks

- [ ] #215 
- [ ] #216

**Comment by aaacafe786** [comment]
https://github.com/Shopify/hydrogen/blob/v1.x-2022-07/packages/hydrogen-ui/src/ExternalVideo.tsx
