### ISSUE TITLE
[S13.1]: Content

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#221]
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

Make a component using Sanity's portable text including:

- containers component (sm/md/lg)
- background colour
- padding/margin controls
- paragraphs
- headings
- blockquote
- image
- list items
- links
- buttons

### Linked Tasks

- [x] #222
- [x] #223 
- [ ] #600

**Comment by stevenbister** [comment]
_May_ have to hold off on starting this one until #233 is merged as it's more dependant on Sanity that some of the other components
