### ISSUE TITLE
Deleting package-lock.json file causes remix apps to error with invalid hooks error

### ISSUE THREAD

**Issue by stevenbister** [Open-Study-College/osc#712]
### Description

When I remove the node_modules and package-lock file to do a fresh install, trying to run a remix apps causes them to fail with Invalid hook call error

### Link to Reproduction

http://localhost:3000

### Steps to reproduce

1. In your terminal run `rm -rf node_modules package-lock.json`
2. Run `npm run setup` (or `npm i`)
3. Run `npm run dev:osc-academic-hub`

You will be greeted with
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/23461173/219942924-cc6c5c2c-4249-497a-ae1b-1b0405dd4ae1.png">

### Release Version

0.42.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

If you `git restore package-lock.json` it and run the install again it stops the error.

I've tried removing `osc-studio` from the monorepo to test as that's the only package that is obviously using a different react version (17) to the remix apps (18). This didn't make a difference however :/ I guess because it's not a "workspace" that makes sense as it shouldn't make it into the root lock file.

I am pretty stumped by this. Removing all packages except for academic hub still causes the app to error, which makes me think there is something deeper going on and for whatever reason the packages aren't being hoisted or linked correctly. I think using a combination of lerna and npm workspaces _might_ be contributing but that is purely speculation.

As an aside I did also notice that `osc-ui` itself doesn't have React as a dependency so must be relying on it from another package, this is a cross package dependency which is an antipattern for monorepos ([see packages have strong boundaries](https://monorepo.guide/thinking-in-monorepos) so potentially another contributor.

**Comment by stevenbister** [comment]
Attempting to move the workspaces into the lerna.json then causes husky to fail to install
```
npm i

> osc@0.42.0 prepare
> husky install

sh: husky: command not found
npm ERR! code 127
npm ERR! path /Users/stevebister/SITES/osc
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevebister/.npm/_logs/2023-02-19T11_46_18_855Z-debug-0.log
```


Whyyyyyyyyy!

**Comment by stevenbister** [comment]
Actually this causes a lot of things to fail when running commands such as `npm run dev:osc-academic-hub`

```
npm run dev:osc-academic-hub

> osc@0.42.0 dev:osc-academic-hub
> lerna run dev --scope '{osc-ui,osc-academic-hub}'

lerna notice cli v6.5.1
lerna notice filter including "{osc-ui,osc-academic-hub}"
lerna info filter [ '{osc-ui,osc-academic-hub}' ]

 >  Lerna (powered by Nx)   Running target dev for 2 projects and 1 task they depend on:

    - osc-academic-hub
    - osc-ui

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> osc-ui:dev

> osc-ui@0.0.0 dev
> run-p dev:*

> osc-ui:build


> osc-ui@0.0.0 build
> rm -rf dist && NODE_ENV=production LOAD_PATH=src rollup --config

[!] Error: Cannot find module '@rollup/plugin-commonjs'
Require stack:
- /Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@rollup/plugin-commonjs'
Require stack:
- /Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Object.require.extensions.<computed> [as .js] (/Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)

> osc-ui@0.0.0 dev:rollup
> LOAD_PATH=src rollup -c -w
[!] Error: Cannot find module '@rollup/plugin-commonjs'
Require stack:
- /Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@rollup/plugin-commonjs'
Require stack:
- /Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/stevebister/SITES/osc/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/stevebister/SITES/osc/packages/osc-ui/rollup.config.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Object.require.extensions.<computed> [as .js] (/Users/stevebister/SITES/osc/node_modules/rollup/dist/shared/loadConfigFile.js:621:20)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)

```

**Comment by stevenbister** [comment]
Have been trying some things out in here which may be leading towards solving these issues
https://github.com/Open-Study-College/osc/tree/refactor/monorepo

**Comment by hi-im-si** [comment]
Some hopefully useful resources/solutions:

- https://robkendal.co.uk/blog/2019-12-22-solving-react-hooks-invalid-hook-call-warning

- https://stackoverflow.com/questions/64283813/invalid-hook-call-on-npm-link-library

- https://github.com/facebook/docusaurus/issues/8091#issuecomment-1269112001

- Remove the ^ from react and react-dom

- https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by stevenbister** [comment]
Was doing a bit of digging and I'm pretty sure the cause of this is down to Storybook. This issue seems to collaborate my thinking: https://github.com/storybookjs/storybook/issues/18559.

Looks like we might have to put up with this until v7 is released unless I can think of something before hand 😅 

Why it currently works I have no idea but it'll probably be too much hassle to drop our react versions down to 17 now

**Comment by stevenbister** [comment]
For reference this is how I came to that conclusion
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/23461173/222671592-8726f567-7e28-4542-a390-77d19a9a6fe0.png">
