### ISSUE TITLE
Save SEN data

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#884]
### Link task to story

Story: https://github.com/Open-Study-College/osc/issues/880

### Description

Save SEN data

presets of common SEN requiremtns like ADHD, dyslexia, dyspraxia, sight impairment etc
Optional text field for details

SYNC to hubspot

**Comment by hi-im-si** [comment]
Data to be stored in our database.
Update information against contact in Hubspot.

Endpoint for listing pre-defined options i.e. Autism, ADHD (easily flagged) and inclusion of free-text field.
Frontend to show checkboxes
